// Generated by scripts/build.mjs from src/; edit the sources, not this file.
(() => {
  // src/hosts.mjs
  var MAX_HOSTS = 16;
  var MAX_WORKSPACES = 8;
  var MAX_PATH = 4096;
  var CONTROL = /[\u0000-\u001f\u007f]/u;
  function hostInvalidReason(value) {
    if (!value || typeof value !== "object" || Array.isArray(value)) return "a host must be an object";
    const unknown = Object.keys(value).find((key) => !["label", "sshHost", "sshUser", "sshPort", "workspaces"].includes(key));
    if (unknown) return `unknown field ${unknown.slice(0, 40)}`;
    if (typeof value.label !== "string" || !value.label.trim() || value.label.length > 40 || CONTROL.test(value.label)) {
      return "label must be 1 to 40 characters";
    }
    if (typeof value.sshHost !== "string" || !value.sshHost || value.sshHost.length > 253 || /\s/u.test(value.sshHost) || value.sshHost.startsWith("-") || value.sshHost.includes("@") || CONTROL.test(value.sshHost)) {
      return "SSH host must be an ssh config alias or a host name, without spaces, @ or a leading dash";
    }
    if (value.sshUser !== void 0 && (typeof value.sshUser !== "string" || !value.sshUser || value.sshUser.length > 64 || /[\s@]/u.test(value.sshUser) || value.sshUser.startsWith("-") || CONTROL.test(value.sshUser))) {
      return "user must be a name without spaces, @ or a leading dash";
    }
    if (value.sshPort !== void 0 && (!Number.isInteger(value.sshPort) || value.sshPort < 1 || value.sshPort > 65535)) {
      return "port must be a number from 1 to 65535";
    }
    const workspaces = value.workspaces ?? [];
    if (!Array.isArray(workspaces) || workspaces.length > MAX_WORKSPACES) return `at most ${MAX_WORKSPACES} folder mappings`;
    const locals = /* @__PURE__ */ new Set();
    for (const workspace of workspaces) {
      if (!workspace || typeof workspace !== "object" || Object.keys(workspace).sort().join() !== "localPath,remotePath") {
        return "a folder mapping has exactly localPath and remotePath";
      }
      if (!isAbsolutePosix(workspace.localPath)) return "the folder on this computer must be an absolute path";
      if (!isAbsolutePosix(workspace.remotePath)) return "the folder on the server must be an absolute path";
      const key = trimSlashes(workspace.localPath);
      if (locals.has(key)) return "each folder on this computer is mapped once";
      locals.add(key);
    }
    return null;
  }
  function normalizeHosts(value) {
    if (!Array.isArray(value)) return [];
    const seen = /* @__PURE__ */ new Set();
    const hosts2 = [];
    for (const host2 of value.slice(0, MAX_HOSTS)) {
      if (hostInvalidReason(host2) !== null || seen.has(host2.label.trim().toLowerCase())) continue;
      seen.add(host2.label.trim().toLowerCase());
      hosts2.push(structuredClone({ ...host2, label: host2.label.trim(), workspaces: host2.workspaces ?? [] }));
    }
    return hosts2;
  }
  function isAbsolutePosix(value) {
    return typeof value === "string" && value.startsWith("/") && value.length <= MAX_PATH && !CONTROL.test(value) && !value.split("/").includes("..");
  }
  function trimSlashes(path) {
    return path === "/" ? path : path.replace(/\/+$/u, "");
  }

  // src/ui/hosts-page.mjs
  var host = window.CanvasTTYPlugin;
  var list = document.querySelector("#list");
  var form = document.querySelector("#form");
  var status = document.querySelector("#status");
  var hosts = [];
  var say = (text) => {
    status.textContent = text;
  };
  async function load() {
    hosts = normalizeHosts(await host.storage.get("hosts"));
    render();
  }
  function render() {
    list.replaceChildren(...hosts.map((entry, index) => {
      const item = document.createElement("li");
      const name = document.createElement("strong");
      name.textContent = entry.label;
      const where = document.createElement("code");
      where.className = "grow";
      const destination = `${entry.sshUser ? `${entry.sshUser}@` : ""}${entry.sshHost}${entry.sshPort ? `:${entry.sshPort}` : ""}`;
      where.textContent = `${destination}  ${entry.workspaces.map((w) => `${w.localPath} \u2192 ${w.remotePath}`).join(", ")}`;
      const check = document.createElement("button");
      check.type = "button";
      check.textContent = "Check";
      check.addEventListener("click", async () => {
        say(`Checking ${entry.label}\u2026`);
        try {
          const answer = await host.service.request("ssh-host", "check", { label: entry.label });
          say(answer.message);
        } catch (error) {
          say(`Check failed: ${error instanceof Error ? error.message : String(error)}`);
        }
      });
      const remove = document.createElement("button");
      remove.type = "button";
      remove.textContent = "Remove";
      remove.addEventListener("click", async () => {
        hosts = hosts.filter((_, other) => other !== index);
        await host.storage.set("hosts", hosts);
        render();
        say(`Removed ${entry.label}.`);
      });
      item.append(name, where, check, remove);
      return item;
    }));
    if (hosts.length === 0) {
      const empty = document.createElement("li");
      empty.textContent = "No servers yet.";
      list.append(empty);
    }
  }
  form.addEventListener("submit", async (event) => {
    event.preventDefault();
    const data = Object.fromEntries(new FormData(form));
    const label = String(data.label).trim();
    const existing = hosts.find((entry) => entry.label.toLowerCase() === label.toLowerCase());
    const mapping = { localPath: String(data.localPath).trim(), remotePath: String(data.remotePath).trim() };
    const workspaces = [...(existing?.workspaces ?? []).filter((w) => w.localPath !== mapping.localPath), mapping];
    const candidate = {
      label,
      sshHost: String(data.sshHost).trim(),
      ...String(data.sshUser).trim() ? { sshUser: String(data.sshUser).trim() } : {},
      ...String(data.sshPort).trim() ? { sshPort: Number(String(data.sshPort).trim()) } : {},
      workspaces
    };
    const problem = hostInvalidReason(candidate);
    if (problem) return say(`Not saved: ${problem}.`);
    hosts = [...hosts.filter((entry) => entry !== existing), candidate];
    await host.storage.set("hosts", hosts);
    render();
    say(`Saved ${label}.`);
  });
  load().catch((error) => say(`Could not load servers: ${error.message}`));
})();
