// Generated by scripts/build.mjs from src/; edit the sources, not this file.

// src/rpc.mjs
import { createInterface } from "node:readline";
function serve({ methods, notifications = {}, onInitialize }) {
  const pending = /* @__PURE__ */ new Map();
  let nextId = 1;
  const send = (message) => process.stdout.write(`${JSON.stringify({ jsonrpc: "2.0", ...message })}
`);
  const callHost = (method, params) => new Promise((resolve3, reject) => {
    const id = nextId++;
    pending.set(id, { resolve: resolve3, reject });
    send({ id, method, params });
  });
  const log = (level, message) => send({ method: "log", params: { level, message: String(message).slice(0, 500) } });
  createInterface({ input: process.stdin }).on("line", (line) => {
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      return;
    }
    if (message.method === "canvastty.initialize") {
      Promise.resolve().then(() => onInitialize?.(message.params, { callHost, log })).catch((error) => log("error", `initialize failed: ${error.message}`));
      return;
    }
    if (message.method === "canvastty.shutdown") process.exit(0);
    if (typeof message.method === "string" && message.id === void 0) {
      Promise.resolve().then(() => notifications[message.method]?.(message.params, { callHost, log })).catch((error) => log("warn", `${message.method}: ${error.message}`));
      return;
    }
    if (typeof message.method === "string") {
      const method = methods[message.method];
      Promise.resolve().then(() => {
        if (!method) throw Object.assign(new Error(`Unknown method: ${message.method}`), { code: -32601 });
        return method(message.params ?? {}, { callHost, log });
      }).then(
        (result) => send({ id: message.id, result: result ?? null }),
        (error) => send({ id: message.id, error: { code: error.code ?? -32e3, message: String(error.message).slice(0, 400) } })
      );
      return;
    }
    const waiter = pending.get(message.id);
    if (!waiter) return;
    pending.delete(message.id);
    if (message.error) waiter.reject(new Error(message.error.message));
    else waiter.resolve(message.result);
  }).on("close", () => process.exit(0));
}

// src/container.mjs
import { randomUUID } from "node:crypto";
import { realpathSync as realpathSync3, statSync as statSync2 } from "node:fs";
import { rm, writeFile } from "node:fs/promises";
import { basename as basename2, join as join3, posix, relative as relative2, resolve as resolve2, sep as sep2 } from "node:path";
import { execFile as execFile3 } from "node:child_process";
import { promisify as promisify2 } from "node:util";

// src/containerSettings.mjs
var CONTAINER_SETTINGS_KEY = "containers";
var CONTAINER_DEFAULTS = Object.freeze({
  engine: "auto",
  // this computer: auto (Docker, then Podman), docker or podman
  remoteEngine: "podman",
  // on a server: podman or docker, by name on the server's PATH
  image: "",
  // an existing image with python3; never pulled
  cpus: 2,
  memoryMb: 2048,
  pids: 512,
  checkCommand: "",
  // capsule checks: run with /bin/sh -c in /workspace
  checkTimeoutSec: 600
});
var IMAGE = /^[A-Za-z0-9][A-Za-z0-9._/:@-]{0,254}$/u;
var NUMBERS = { cpus: [0.1, 64], memoryMb: [64, 262144], pids: [16, 65536], checkTimeoutSec: [10, 3600] };
function containerSettingsInvalidReason(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "settings must be an object";
  const unknown = Object.keys(value).find((key) => !(key in CONTAINER_DEFAULTS));
  if (unknown) return `unknown field ${unknown.slice(0, 40)}`;
  if (value.engine !== void 0 && !["auto", "docker", "podman"].includes(value.engine)) return "engine must be auto, docker or podman";
  if (value.remoteEngine !== void 0 && !["docker", "podman"].includes(value.remoteEngine)) return "server engine must be docker or podman";
  if (value.image !== void 0 && value.image !== "" && !imageValid(value.image)) return "image must be a name like python:3.12-slim (letters, digits, . _ / : @ -)";
  for (const [key, [min, max]] of Object.entries(NUMBERS)) {
    if (value[key] === void 0) continue;
    if (typeof value[key] !== "number" || !Number.isFinite(value[key]) || value[key] < min || value[key] > max) return `${key} must be a number from ${min} to ${max}`;
    if (key !== "cpus" && !Number.isInteger(value[key])) return `${key} must be a whole number`;
  }
  if (value.checkCommand !== void 0 && (typeof value.checkCommand !== "string" || value.checkCommand.length > 2e3 || value.checkCommand.includes("\0"))) {
    return "the check command is at most 2000 characters";
  }
  return null;
}
function imageValid(image) {
  return typeof image === "string" && IMAGE.test(image) && !image.includes("..");
}
function normalizeContainerSettings(value) {
  if (value === void 0 || value === null || containerSettingsInvalidReason(value) !== null) return { ...CONTAINER_DEFAULTS };
  return { ...CONTAINER_DEFAULTS, ...value };
}

// src/engine.mjs
import { execFile, spawn } from "node:child_process";
import { mkdirSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { delimiter, join } from "node:path";

// src/bootstrap.mjs
var BOOTSTRAP = String.raw`
import os, sys, json, stat, signal, tempfile
ENV = {'PATH': '/usr/local/bin:/usr/bin:/bin', 'HOME': '/tmp', 'TERM': 'xterm-256color', 'LANG': 'C.UTF-8'}

def fail(reason):
    sys.stderr.write('CanvasTTY container check failed: ' + reason + '.\n'); sys.stderr.flush(); os._exit(78)

def privileges():
    with open('/proc/self/status') as f: status = dict(line.split(':', 1) for line in f if ':' in line)
    if status.get('NoNewPrivs', '').strip() != '1': fail('no-new-privileges is off')
    if any(int(status.get(key, '-1').strip(), 16) != 0 for key in ['CapInh', 'CapPrm', 'CapEff', 'CapBnd', 'CapAmb']): fail('capabilities are not all dropped')

def limits(requested):
    with open('/proc/self/cgroup') as f:
        if f.read().strip() != '0::/': fail('the cgroup is not private')
    with open('/sys/fs/cgroup/cpu.max') as f: cpu = f.read().split()
    if len(cpu) != 2 or cpu[0] == 'max' or int(cpu[0]) <= 0 or int(cpu[1]) <= 0 or int(cpu[0]) / int(cpu[1]) > requested['cpus'] + 0.000001: fail('CPU limit')
    for name, maximum in [('memory.max', requested['memoryMb'] * 1048576), ('pids.max', requested['pids'])]:
        with open('/sys/fs/cgroup/' + name) as f: value = f.read().strip()
        if value == 'max' or int(value) <= 0 or int(value) > maximum: fail(name + ' limit')

def mounts():
    seen = set()
    with open('/proc/self/mountinfo') as f:
        for line in f:
            fields = line.split(); mount = fields[4].replace('\\040', ' '); options = fields[5].split(',')
            optional = fields[6:fields.index('-')]
            if mount == '/' and 'ro' not in options: fail('the root filesystem is writable')
            if mount == '/tmp' and any(flag not in options for flag in ['rw', 'nosuid', 'nodev', 'noexec']): fail('/tmp is not rw,nosuid,nodev,noexec')
            if mount == '/workspace' and ('rw' not in options or any(item.startswith('shared:') for item in optional)): fail('/workspace is read-only or shared')
            if mount == '/run/.containerenv' and 'ro' not in options: fail('container metadata is writable')
            if mount in ['/', '/tmp', '/workspace']: seen.add(mount); continue
            if mount in ['/etc/hosts', '/etc/hostname', '/etc/resolv.conf', '/run/.containerenv'] or mount.split('/')[1] in ['proc', 'sys', 'dev']: continue
            fail('unexpected mount ' + mount[:80])
    if len(seen) != 3: fail('a required mount is missing')

def workspace(marker):
    if os.path.realpath('/workspace') != '/workspace' or not os.path.isdir('/workspace'): fail('no /workspace folder')
    name = marker['name']
    if not name.startswith('.canvastty-container-') or '/' in name or len(name) != 57: fail('invalid marker')
    fd = os.open('/workspace/' + name, os.O_RDONLY | os.O_NOFOLLOW)
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1 or os.read(fd, 129).decode('ascii') != marker['token']: fail('/workspace is not the prepared folder')
    finally: os.close(fd)
    os.unlink('/workspace/' + name)
    fd, probe = tempfile.mkstemp(prefix='.canvastty-write-', dir='/workspace'); os.close(fd); os.unlink(probe)

def run():
    raw = os.environ.get('CANVASTTY_CONTAINER_RECIPE', '')
    if len(raw) > 16384: fail('recipe too large')
    recipe = json.loads(raw)
    privileges(); limits(recipe['limits']); mounts(); workspace(recipe['marker'])
    if recipe['mode'] == 'check':
        command = recipe['command']
        if not isinstance(command, str) or not command or len(command) > 4096: fail('invalid check command')
        os.chdir('/workspace'); sys.stdout.flush()
        os.execve('/bin/sh', ['/bin/sh', '-c', command], ENV)
    if recipe['mode'] != 'hold': fail('unknown mode')
    signal.signal(signal.SIGTERM, lambda *_: os._exit(0)); signal.signal(signal.SIGINT, lambda *_: os._exit(0))
    while True: signal.pause()

try: run()
except SystemExit: raise
except Exception: fail('the recipe or the container could not be verified')
`;
var EXEC = String.raw`
import os, sys, json
def fail(reason):
    sys.stderr.write('CanvasTTY container check failed: ' + reason + '.\n'); sys.stderr.flush(); os._exit(78)
try:
    r = json.loads(os.environ.get('CANVASTTY_CONTAINER_RECIPE', ''))
    s = dict(line.split(':', 1) for line in open('/proc/self/status') if ':' in line)
    if s['NoNewPrivs'].strip() != '1' or any(int(s[key].strip(), 16) for key in ['CapInh', 'CapPrm', 'CapEff', 'CapBnd', 'CapAmb']): fail('privileges')
    cwd = r['cwd']
    if (cwd != '/workspace' and not cwd.startswith('/workspace/')) or os.path.realpath(cwd) != cwd or not os.path.isdir(cwd): fail('no folder ' + cwd[:80])
    env = {'PATH': '/usr/local/bin:/usr/bin:/bin', 'HOME': '/tmp', 'TERM': os.environ.get('TERM', 'xterm-256color'), 'LANG': 'C.UTF-8'}
    for name in r.get('pass', []):
        if name in os.environ: env[name] = os.environ[name]
    name = r['command']
    if name == 'shell':
        args = ['-l']; program = next((p for p in ['/bin/bash', '/bin/sh'] if os.access(p, os.X_OK)), '')
    else:
        args = r['args']; program = '' if '/' in name else next((d + '/' + name for d in env['PATH'].split(':') if os.access(d + '/' + name, os.X_OK)), '')
    if not program: fail(name[:40] + ' is not installed in the image')
    os.chdir(cwd); os.execve(program, [program] + args, env)
except SystemExit: raise
except Exception: fail('the recipe could not be verified')
`;

// src/engine.mjs
var PLUGIN_ID = "canvastty-environments";
var PLUGIN_LABEL = "io.canvastty.plugin";
var SESSION_LABEL = "io.canvastty.session";
var MARKER_PREFIX = ".canvastty-container-";
var HEX64 = /^[0-9a-f]{64}$/u;
var NAME = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/u;
var markerName = (uuid) => `${MARKER_PREFIX}${uuid}`;
function parseEngineInfo(kind, data) {
  if (!data || typeof data !== "object") throw new Error("The container engine returned no information.");
  if (kind === "docker") {
    const options = Array.isArray(data.SecurityOptions) ? data.SecurityOptions.map(String) : [];
    if (data.OSType !== "linux" || String(data.CgroupVersion) !== "2" || data.CpuCfsPeriod !== true || data.CpuCfsQuota !== true || data.MemoryLimit !== true || data.PidsLimit !== true) {
      throw new Error("Docker must run Linux containers with cgroup v2 CPU, memory and PID limits.");
    }
    if (options.some((option) => option.includes("userns"))) throw new Error("Docker with user-namespace remapping is not supported.");
    return { rootless: options.some((option) => option.includes("name=rootless")), name: String(data.Name ?? "docker").slice(0, 80) };
  }
  const host2 = data.host ?? {};
  if (host2.os !== "linux" || host2.cgroupVersion !== "v2" || !Array.isArray(host2.cgroupControllers) || ["cpu", "memory", "pids"].some((controller) => !host2.cgroupControllers.includes(controller))) {
    throw new Error("Podman must run with cgroup v2 and delegated cpu, memory and pids controllers.");
  }
  return { rootless: host2.security?.rootless === true, name: String(host2.hostname ?? "podman").slice(0, 80) };
}
function parseImage(raw) {
  const list = JSON.parse(raw);
  const image = Array.isArray(list) && list.length === 1 ? list[0] : null;
  const id = String(image?.Id ?? "").replace(/^sha256:/u, "");
  if (!image || !HEX64.test(id)) throw new Error("The engine did not identify the image.");
  if (image.Os !== "linux") throw new Error("The image is not a Linux image.");
  if (image.Config?.Volumes && Object.keys(image.Config.Volumes).length) throw new Error("The image declares volumes; use an image without VOLUME.");
  return { id };
}
function containerUser(kind, rootless, owner) {
  if (kind === "podman" && rootless) return "keep-id";
  if (kind === "docker" && rootless) return "0:0";
  if (!/^\d{1,10}:\d{1,10}$/u.test(String(owner))) throw new Error("The workspace owner is unknown.");
  return owner;
}
function recipe({ mode, limits, marker, command }) {
  return JSON.stringify({ mode, limits: { cpus: limits.cpus, memoryMb: limits.memoryMb, pids: limits.pids }, marker, ...mode === "check" ? { command } : {} });
}
function createArgs({ kind, name, sessionId, workspace, user, network, limits, image, recipe: text }) {
  if (!["docker", "podman"].includes(kind)) throw new Error("Unknown container engine.");
  if (!workspace.startsWith("/") || /[,\u0000-\u001f\u007f]/u.test(workspace)) throw new Error("The workspace path cannot be mounted (commas and control characters are not allowed).");
  if (!["none", "bridge"].includes(network)) throw new Error("The network must be none or bridge.");
  const mount = `type=bind,src=${workspace},dst=/workspace,${kind === "docker" ? "bind-recursive=disabled" : "bind-nonrecursive"},bind-propagation=rprivate`;
  return [
    "container",
    "create",
    "--name",
    name,
    "--label",
    `${PLUGIN_LABEL}=${PLUGIN_ID}`,
    "--label",
    `${SESSION_LABEL}=${sessionId}`,
    "--pull=never",
    "--read-only",
    "--cap-drop=ALL",
    "--security-opt=no-new-privileges",
    `--network=${network}`,
    `--cpus=${limits.cpus}`,
    `--memory=${limits.memoryMb}m`,
    `--pids-limit=${limits.pids}`,
    "--cgroupns=private",
    "--restart=no",
    "--stop-signal=SIGTERM",
    "--log-driver=none",
    `--tmpfs=/tmp:rw,nosuid,nodev,noexec,size=256m,mode=1777${kind === "podman" ? ",notmpcopyup" : ""}`,
    "--workdir=/workspace",
    `--mount=${mount}`,
    "--entrypoint",
    "python3",
    ...kind === "docker" ? ["--no-healthcheck"] : [
      "--health-cmd=none",
      "--image-volume=ignore",
      "--http-proxy=false",
      "--unsetenv-all",
      "--read-only-tmpfs=false",
      "--systemd=false",
      "--sdnotify=ignore"
    ],
    ...user === "keep-id" ? ["--userns=keep-id"] : [`--user=${user}`],
    `--env=CANVASTTY_CONTAINER_RECIPE=${text}`,
    "--env=HOME=/tmp",
    "--env=PATH=/usr/local/bin:/usr/bin:/bin",
    "--env=TERM=xterm-256color",
    "--env=LANG=C.UTF-8",
    image,
    "-I",
    "-S",
    "-c",
    BOOTSTRAP
  ];
}
function verifyInspection(expected, raw) {
  const list = typeof raw === "string" ? JSON.parse(raw) : raw;
  const v = Array.isArray(list) ? list[0] : list;
  if (!v || typeof v !== "object") throw new Error("The engine returned no container.");
  const c = v.Config ?? {}, h = v.HostConfig ?? {}, { kind, limits } = expected;
  const differs = (what) => {
    throw new Error(`The container differs from its recipe (${what}); it is not used.`);
  };
  if (!HEX64.test(String(v.Id)) || expected.containerId && v.Id !== expected.containerId) differs("id");
  if (String(v.Name).replace(/^\//u, "") !== expected.name) differs("name");
  if (String(v.Image).replace(/^sha256:/u, "") !== expected.imageId) differs("image");
  if (c.Labels?.[PLUGIN_LABEL] !== PLUGIN_ID || c.Labels?.[SESSION_LABEL] !== expected.sessionId) differs("labels");
  if (v.Path !== "python3" || JSON.stringify(v.Args) !== JSON.stringify(["-I", "-S", "-c", BOOTSTRAP])) differs("entrypoint");
  if (c.WorkingDir !== "/workspace" || expected.user !== "keep-id" && c.User !== expected.user) differs("user or folder");
  if (c.Healthcheck && JSON.stringify(c.Healthcheck.Test) !== JSON.stringify(["NONE"])) differs("healthcheck");
  const empty = (value) => value === void 0 || value === null || value === "" || Array.isArray(value) && value.length === 0;
  const capsDropped = kind === "docker" ? Array.isArray(h.CapDrop) && h.CapDrop.some((cap) => /^all$/iu.test(cap)) : (v.EffectiveCaps === null || Array.isArray(v.EffectiveCaps) && !v.EffectiveCaps.length) && (v.BoundingCaps === null || Array.isArray(v.BoundingCaps) && !v.BoundingCaps.length);
  if (h.Privileged !== false || h.ReadonlyRootfs !== true || !capsDropped || !empty(h.CapAdd)) differs("privileges");
  if (!Array.isArray(h.SecurityOpt) || !h.SecurityOpt.some((option) => option === "no-new-privileges" || option === "no-new-privileges=true")) differs("no-new-privileges");
  if (h.NetworkMode !== expected.network) differs("network");
  const cpus = h.NanoCpus > 0 ? h.NanoCpus / 1e9 : h.CpuPeriod > 0 ? h.CpuQuota / h.CpuPeriod : NaN;
  if (!(cpus > 0 && cpus <= limits.cpus + 1e-6) || !(h.Memory > 0 && h.Memory <= limits.memoryMb * 1048576) || !(h.PidsLimit > 0 && h.PidsLimit <= limits.pids)) differs("limits");
  if (!empty(h.VolumesFrom) || !empty(h.Devices) || !empty(h.DeviceRequests) || ["PidMode", "IpcMode", "UTSMode"].some((key) => h[key] === "host")) differs("host sharing");
  if ((kind === "docker" ? h.CgroupnsMode : h.CgroupMode) !== "private" || h.RestartPolicy?.Name !== "no") differs("cgroup or restart");
  const mounts = Array.isArray(v.Mounts) ? v.Mounts : differs("mounts");
  if (mounts.some((mount) => mount.Type === "tmpfs" && mount.Destination !== "/tmp")) differs("temporary mount");
  const binds = mounts.filter((mount) => mount.Type !== "tmpfs");
  if (binds.length !== 1 || binds[0].Type !== "bind" || binds[0].Source !== expected.workspace || binds[0].Destination !== "/workspace" || binds[0].RW !== true || binds[0].Propagation !== "rprivate") differs("workspace mount");
  if (kind === "docker" && h.Mounts?.[0]?.BindOptions?.NonRecursive !== true) differs("recursive mount");
  if (kind === "podman" && (!Array.isArray(binds[0].Options) || !binds[0].Options.includes("bind") || binds[0].Options.includes("rbind"))) differs("recursive mount");
  const tmp = typeof h.Tmpfs?.["/tmp"] === "string" ? h.Tmpfs["/tmp"].split(",") : [];
  const size = tmp.find((option) => option.startsWith("size="))?.match(/^size=(\d+)([kmg]?)$/iu);
  const bytes = size ? Number(size[1]) * { "": 1, k: 1024, m: 1024 ** 2, g: 1024 ** 3 }[size[2].toLowerCase()] : NaN;
  if (Object.keys(h.Tmpfs ?? {}).length !== 1 || !(bytes > 0 && bytes <= 256 * 1024 ** 2) || !["noexec", "nosuid", "nodev"].every((flag) => tmp.includes(flag))) differs("/tmp");
  const state = v.State ?? {};
  return { containerId: v.Id, running: state.Running === true, status: String(state.Status ?? ""), exitCode: Number.isInteger(state.ExitCode) ? state.ExitCode : null };
}
function execArgs({ containerId, cwd, command, args = [], pass = [] }) {
  if (!HEX64.test(String(containerId))) throw new Error("The container id is unreadable.");
  const names = pass.filter((name) => NAME.test(name) && !name.startsWith("CANVASTTY_")).slice(0, 32);
  const text = JSON.stringify({ cwd, command, args, pass: names });
  return ["exec", "-it", "-e", `CANVASTTY_CONTAINER_RECIPE=${text}`, ...names.flatMap((name) => ["-e", name]), containerId, "python3", "-I", "-S", "-c", EXEC];
}
var safeEnvironment = () => Object.fromEntries(["PATH", "HOME", "USER", "LOGNAME", "LANG", "LC_ALL", "TMPDIR", "XDG_RUNTIME_DIR", "XDG_CONFIG_HOME", "XDG_DATA_HOME"].flatMap((name) => process.env[name] === void 0 ? [] : [[name, process.env[name]]]));
function findExecutable(name, extra) {
  const dirs = [...String(process.env.PATH ?? "").split(delimiter), ...extra].filter(Boolean);
  for (const dir of dirs) {
    const path = join(dir, name);
    try {
      if (statSync(path).isFile()) return path;
    } catch {
    }
  }
  return null;
}
function dockerSocket() {
  const fromEnv = String(process.env.DOCKER_HOST ?? "");
  const candidates = [
    fromEnv.startsWith("unix://") ? fromEnv.slice(7) : "",
    join(homedir(), ".docker/run/docker.sock"),
    "/var/run/docker.sock",
    join(homedir(), ".colima/default/docker.sock"),
    join(homedir(), ".orbstack/run/docker.sock"),
    join(homedir(), ".rd/docker.sock")
  ];
  return candidates.find((path) => {
    try {
      return path && statSync(path).isSocket();
    } catch {
      return false;
    }
  }) ?? null;
}
function runEngine(engine, words, { timeoutMs = 2e4, env = {} } = {}) {
  return new Promise((resolve3, reject) => {
    execFile(
      engine.exe,
      [...engine.prefix, ...words],
      { env: { ...safeEnvironment(), ...env }, timeout: timeoutMs, killSignal: "SIGKILL", maxBuffer: 4 * 1024 * 1024, encoding: "utf8" },
      (error, stdout, stderr) => {
        if (!error) return resolve3(stdout);
        const detail = String(stderr || error.message).replace(/\s+/gu, " ").trim().slice(0, 300);
        reject(Object.assign(new Error(error.killed ? `${engine.kind} ${words[1] ?? words[0]} did not finish in time.` : detail || `${engine.kind} failed.`), { exitCode: error.code }));
      }
    );
  });
}
function attachEngine(engine, containerId, { timeoutMs, maxBytes = 256 * 1024, onChild }) {
  return new Promise((resolve3) => {
    const child = spawn(engine.exe, [...engine.prefix, "container", "start", "--attach", containerId], { env: safeEnvironment(), stdio: ["ignore", "pipe", "pipe"] });
    onChild?.(child);
    let output = "", timedOut = false;
    const keep = (chunk) => {
      output = (output + chunk).slice(-maxBytes);
    };
    child.stdout.setEncoding("utf8").on("data", keep);
    child.stderr.setEncoding("utf8").on("data", keep);
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, timeoutMs);
    child.on("error", (error) => {
      clearTimeout(timer);
      resolve3({ code: null, output: error.message, timedOut });
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve3({ code, output, timedOut });
    });
  });
}
var DOCKER_DIRS = ["/usr/local/bin", "/opt/homebrew/bin", "/Applications/Docker.app/Contents/Resources/bin", "/usr/bin"];
var PODMAN_DIRS = ["/opt/podman/bin", "/opt/homebrew/bin", "/usr/local/bin", "/usr/bin"];
async function detectLocalEngine({ preferred = "auto", dataDir: dataDir2, run: run2 = runEngine }) {
  const reasons = [];
  if (preferred === "auto" || preferred === "docker") {
    const exe = findExecutable("docker", DOCKER_DIRS);
    const socket = exe ? dockerSocket() : null;
    if (!exe) reasons.push("Docker is not installed");
    else if (!socket) reasons.push("Docker is installed but not running (no socket)");
    else {
      const config = join(dataDir2, "engine", "docker-config");
      mkdirSync(config, { recursive: true, mode: 448 });
      const engine = { kind: "docker", exe, prefix: ["--config", config, "--host", `unix://${socket}`] };
      try {
        return { ...engine, ...parseEngineInfo("docker", JSON.parse(await run2(engine, ["info", "--format", "{{json .}}"], { timeoutMs: 6e3 }))) };
      } catch (error) {
        reasons.push(`Docker: ${error.message}`);
      }
    }
  }
  if (preferred === "auto" || preferred === "podman") {
    const exe = findExecutable("podman", PODMAN_DIRS);
    if (!exe) reasons.push("Podman is not installed");
    else {
      const engine = { kind: "podman", exe, prefix: [] };
      try {
        return { ...engine, ...parseEngineInfo("podman", JSON.parse(await run2(engine, ["info", "--format=json"], { timeoutMs: 6e3 }))) };
      } catch (error) {
        reasons.push(`Podman: ${String(error.message).includes("machine") || String(error.message).includes("connect") ? "not running (start its machine first)" : error.message}`);
      }
    }
  }
  throw new Error(`No container engine can be used on this computer: ${reasons.join("; ")}.`);
}

// src/hosts.mjs
function remoteArgs(args, localRoots) {
  const roots = localRoots.filter((root) => typeof root === "string" && root.length > 1).map(trimSlashes);
  const local = (word) => /^\s*[{[]/u.test(word) || roots.some((root) => word.includes(root));
  const kept = [];
  for (const word of args) {
    if (typeof word !== "string" || word.includes("\0")) throw new Error("Invalid agent argument.");
    if (!local(word)) {
      kept.push(word);
      continue;
    }
    const previous = kept.at(-1);
    if (previous !== void 0 && /^-{1,2}[A-Za-z][\w-]*$/u.test(previous)) kept.pop();
  }
  return kept;
}
function trimSlashes(path) {
  return path === "/" ? path : path.replace(/\/+$/u, "");
}

// src/sshHost.mjs
import { realpathSync } from "node:fs";
import { homedir as homedir2, tmpdir } from "node:os";
import { dirname } from "node:path";
function localRootsFor(dataDir2) {
  return [...new Set([
    homedir2(),
    tmpdir(),
    safeRealpath(tmpdir()),
    "/private/var/folders",
    "/var/folders",
    dirname(dirname(dataDir2)),
    appRoot(process.execPath)
  ].filter(Boolean))];
}
function safeRealpath(path) {
  try {
    return realpathSync(path);
  } catch {
    return null;
  }
}
function appRoot(execPath) {
  const bundle = execPath.indexOf(".app/");
  return bundle > 0 ? execPath.slice(0, bundle + 4) : dirname(execPath);
}

// src/worktree.mjs
import { execFile as execFile2 } from "node:child_process";
import { existsSync, realpathSync as realpathSync2 } from "node:fs";
import { basename, join as join2, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";
var run = promisify(execFile2);
var git = async (cwd, ...args) => (await run("git", ["-C", cwd, ...args], { timeout: 1e4 })).stdout.trim();
function createWorktreeEnvironment({ dataDir: dataDir2 }) {
  const root = resolve(dataDir2, "worktrees");
  function owned(ref) {
    const dir = typeof ref?.dir === "string" ? resolve(ref.dir) : "";
    if (!dir.startsWith(root + sep)) throw new Error("This worktree does not belong to the plugin.");
    return { ...ref, dir };
  }
  return {
    async prepare({ sessionId, cwd, options = {} }) {
      const repo = await git(cwd, "rev-parse", "--show-toplevel").catch(() => null);
      if (!repo) return { refuse: { reason: `${cwd} is not inside a git repository.` } };
      const base = await git(repo, "rev-parse", "--verify", "-q", "HEAD^{commit}").catch(() => null);
      if (!base) return { refuse: { reason: `${repo} has no commit yet; commit once before starting a worktree.` } };
      const branch = String(options.branch ?? "").trim() || `canvastty/${String(sessionId).slice(0, 8)}`;
      if (!await git(repo, "check-ref-format", "--branch", branch).catch(() => null)) {
        return { refuse: { reason: `${branch} is not a valid branch name.` } };
      }
      const dir = join2(root, `${basename(repo)}-${String(sessionId).slice(0, 8)}`);
      const exists = await git(repo, "rev-parse", "--verify", "--quiet", `refs/heads/${branch}`).then(() => true, () => false);
      try {
        await git(repo, "worktree", "add", "--quiet", ...exists ? [dir, branch] : ["-b", branch, dir]);
      } catch (error) {
        return { refuse: { reason: `git worktree add failed: ${String(error.stderr || error.message).trim().slice(0, 200)}` } };
      }
      const started = await git(dir, "rev-parse", "HEAD");
      const inside = relative(repo, realpathSync2(cwd));
      const sub = inside.startsWith("..") ? "" : inside;
      return { ref: { repo, dir, branch, createdBranch: !exists, sub, base: started }, label: `worktree ${branch}`, cwd: join2(dir, sub) };
    },
    async resume({ ref }) {
      const { dir } = owned(ref);
      if (!existsSync(dir)) return { stopped: { reason: `The worktree folder ${dir} no longer exists.` } };
      const inside = await git(dir, "rev-parse", "--is-inside-work-tree").catch(() => "");
      return inside === "true" ? { ok: true } : { stopped: { reason: `${dir} is no longer a git worktree.` } };
    },
    wrap({ ref, command, args }) {
      const { dir, sub } = owned(ref);
      return { command, args, cwd: join2(dir, sub ?? "") };
    },
    async release({ ref, keepData }) {
      if (keepData) return {};
      const { repo, dir, branch, createdBranch } = owned(ref);
      await git(repo, "worktree", "remove", "--force", dir);
      if (createdBranch) await git(repo, "branch", "-D", branch).catch(() => void 0);
      return {};
    },
    async describe({ ref }) {
      const { dir } = owned(ref);
      const branch = await git(dir, "rev-parse", "--abbrev-ref", "HEAD").catch(() => ref.branch);
      return { label: `worktree ${branch}`, detail: dir };
    },
    /** For "Collect changes": the worktree folder and the commit it started from, after the ownership check. */
    owned
  };
}

// src/container.mjs
var PREPARE_BUDGET_MS = 12500;
var READY_MS = 8e3;
var UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u;
var gitTop = async (cwd) => (await promisify2(execFile3)("git", ["-C", cwd, "rev-parse", "--show-toplevel"], { timeout: 5e3 })).stdout.trim();
async function startAndWait({ start, markerGone, timeoutMs }) {
  const attached = start();
  const deadline = Date.now() + timeoutMs;
  let exited = null;
  attached.done.then((result) => {
    exited = result;
  });
  while (Date.now() < deadline) {
    if (await markerGone()) {
      await new Promise((r) => setTimeout(r, 150));
      if (!exited) {
        attached.detach();
        return { ok: true };
      }
    }
    if (exited) break;
    await new Promise((r) => setTimeout(r, 100));
  }
  attached.detach();
  const output = String(exited?.output ?? "").replace(/\s+/gu, " ").trim();
  const reason = output.match(/CanvasTTY container check failed: [^\n]*/u)?.[0] ?? (output.slice(-300) || (exited ? `the container exited (${exited.code})` : "the container did not become ready in time"));
  return { ok: false, reason };
}
function createContainerEnvironment({ dataDir: dataDir2, readSettings: readSettings2, detect = detectLocalEngine, run: run2 = runEngine, attach = attachEngine }) {
  const worktrees = createWorktreeEnvironment({ dataDir: dataDir2 });
  const worktreesRoot = resolve2(dataDir2, "worktrees");
  const localRoots = localRootsFor(dataDir2);
  const pending = /* @__PURE__ */ new Map();
  function owned(ref) {
    if (!ref || typeof ref !== "object" || !["docker", "podman"].includes(ref.engine?.kind) || typeof ref.engine.exe !== "string" || !Array.isArray(ref.engine.prefix) || !/^canvastty-[0-9a-f-]{36}$/u.test(String(ref.name)) || !UUID.test(String(ref.token)) || typeof ref.workspace !== "string" || !ref.workspace.startsWith("/") || String(ref.sub ?? "").split("/").includes("..")) {
      throw new Error("This card's container ref is unreadable.");
    }
    if (ref.worktree) worktrees.owned(ref.worktree);
    if (ref.mode === "copy" && !resolve2(ref.workspace).startsWith(worktreesRoot + sep2)) throw new Error("This container's workspace does not belong to the plugin.");
    return ref;
  }
  const expectation = (ref, sessionId) => ({
    kind: ref.engine.kind,
    name: ref.name,
    sessionId,
    workspace: ref.workspace,
    user: ref.user,
    network: ref.network,
    limits: ref.limits,
    imageId: ref.imageId,
    containerId: ref.containerId
  });
  const writeMarker = (ref) => writeFile(join3(ref.workspace, markerName(ref.token)), ref.token, { mode: 384 });
  const markerGone = (ref) => async () => {
    try {
      statSync2(join3(ref.workspace, markerName(ref.token)));
      return false;
    } catch {
      return true;
    }
  };
  const startAttached = (engine, containerId) => () => {
    const controller = { kill: null };
    const done = attach(engine, containerId, { timeoutMs: READY_MS + 2e3, onChild: (child) => {
      controller.kill = () => child.kill("SIGKILL");
    } });
    return { done, detach: () => controller.kill?.() };
  };
  async function removeCardContainers(engine, sessionId, created) {
    if (created) await created.catch(() => void 0);
    for (let attempt = 0; attempt < 3; attempt++) {
      const ids = (await run2(engine, ["container", "ls", "--all", "--quiet", "--no-trunc", "--filter", `label=${SESSION_LABEL}=${sessionId}`], { timeoutMs: 8e3 }).catch(() => "")).split(/\s+/u).filter(Boolean);
      if (!ids.length) return;
      await run2(engine, ["container", "rm", "--force", ...ids], { timeoutMs: 1e4 }).catch(() => void 0);
    }
  }
  async function doPrepare({ sessionId, cwd, options = {} }) {
    const deadline = Date.now() + PREPARE_BUDGET_MS;
    const left = () => {
      const ms = deadline - Date.now();
      if (ms <= 500) throw new Error("preparing the container took too long");
      return ms;
    };
    const settings = normalizeContainerSettings(await readSettings2());
    const image = String(options.image ?? "").trim() || settings.image;
    if (!image) return { refuse: { reason: "No container image is set: choose one in the plugin's Settings (an existing image with python3), or type it in the launcher." } };
    if (!imageValid(image)) return { refuse: { reason: `${image.slice(0, 80)} is not a valid image name.` } };
    let engine;
    try {
      engine = await detect({ preferred: settings.engine, dataDir: dataDir2, run: run2 });
    } catch (error) {
      return { refuse: { reason: error.message } };
    }
    const mode = options.workspace === "project" ? "project" : "copy";
    const network = options.network === true ? "bridge" : "none";
    const limits = { cpus: settings.cpus, memoryMb: settings.memoryMb, pids: settings.pids };
    let wref = null, workspace, sub, created = null;
    const id = randomUUID(), name = `canvastty-${id}`, token = randomUUID();
    try {
      if (mode === "copy") {
        const prepared = await worktrees.prepare({ sessionId, cwd, options: { branch: "" } });
        if (prepared.refuse) return { refuse: { reason: `${prepared.refuse.reason} (Or start it with Workspace = the project folder.)` } };
        wref = prepared.ref;
        workspace = realpathSync3(wref.dir);
        sub = wref.sub ?? "";
      } else {
        workspace = realpathSync3(await gitTop(cwd).catch(() => cwd));
        sub = relative2(workspace, realpathSync3(cwd));
        if (sub.startsWith("..")) sub = "";
      }
      await removeCardContainers(engine, sessionId);
      const info = statSync2(workspace);
      const user = containerUser(engine.kind, engine.rootless, `${info.uid}:${info.gid}`);
      const { id: imageId } = parseImage(await run2(engine, ["image", "inspect", image], { timeoutMs: left() }).catch((error) => {
        throw new Error(`the image ${image} is not on this computer (it is never pulled; pull or build it first): ${error.message}`);
      }));
      const ref = {
        v: 1,
        engine: { kind: engine.kind, exe: engine.exe, prefix: engine.prefix },
        name,
        token,
        image,
        imageId,
        network,
        limits,
        user,
        mode,
        workspace,
        sub,
        ...wref ? { worktree: wref } : {}
      };
      await writeMarker(ref);
      created = run2(engine, createArgs({
        kind: engine.kind,
        name,
        sessionId,
        workspace,
        user,
        network,
        limits,
        image,
        recipe: recipe({ mode: "hold", limits, marker: { name: markerName(token), token } })
      }), { timeoutMs: left() }).then((out) => out.trim());
      ref.containerId = await created;
      verifyInspection(expectation(ref, sessionId), await run2(engine, ["container", "inspect", ref.containerId], { timeoutMs: left() }));
      const ready2 = await startAndWait({ start: startAttached(engine, ref.containerId), markerGone: markerGone(ref), timeoutMs: Math.min(READY_MS, left()) });
      if (!ready2.ok) throw new Error(ready2.reason);
      const state = verifyInspection(expectation(ref, sessionId), await run2(engine, ["container", "inspect", ref.containerId], { timeoutMs: left() }));
      if (!state.running) throw new Error("the container stopped right after its checks");
      return { ref, label: `container ${image}`.slice(0, 80), cwd: join3(workspace, sub) };
    } catch (error) {
      if (created || engine) await removeCardContainers(engine, sessionId, created);
      if (workspace) await rm(join3(workspace, markerName(token)), { force: true }).catch(() => void 0);
      if (wref) await worktrees.release({ ref: wref, keepData: false }).catch(() => void 0);
      return { refuse: { reason: `The container could not be started: ${String(error.message).slice(0, 400)}` } };
    }
  }
  return {
    async prepare(params) {
      const task = doPrepare(params);
      pending.set(params.sessionId, task);
      try {
        return await task;
      } finally {
        if (pending.get(params.sessionId) === task) pending.delete(params.sessionId);
      }
    },
    async resume({ sessionId, ref }) {
      const r = owned(ref);
      let state;
      try {
        state = verifyInspection(expectation(r, sessionId), await run2(r.engine, ["container", "inspect", r.containerId], { timeoutMs: 6e3 }));
      } catch (error) {
        return { stopped: { reason: /no such|not found|no container/iu.test(error.message) ? `The container ${r.name} no longer exists.` : `The container cannot be used: ${error.message}` } };
      }
      if (state.running) return { ok: true };
      try {
        statSync2(r.workspace);
      } catch {
        return { stopped: { reason: `The container's workspace ${r.workspace} no longer exists.` } };
      }
      await writeMarker(r);
      const ready2 = await startAndWait({ start: startAttached(r.engine, r.containerId), markerGone: markerGone(r), timeoutMs: READY_MS });
      if (!ready2.ok) {
        await rm(join3(r.workspace, markerName(r.token)), { force: true }).catch(() => void 0);
        return { stopped: { reason: `The container did not start again: ${ready2.reason}` } };
      }
      return { ok: true };
    },
    wrap({ ref, provider, command, args = [], env = {}, secretEnvNames = [] }) {
      const r = owned(ref);
      const cwd = posix.join("/workspace", r.sub ?? "");
      const program = provider === "terminal" ? "shell" : basename2(String(command));
      const words = execArgs({
        containerId: r.containerId,
        cwd,
        command: program,
        args: provider === "terminal" ? [] : remoteArgs(args, localRoots),
        pass: [...Object.keys(env), ...secretEnvNames, "COLORTERM"]
      });
      return { command: r.engine.exe, args: [...r.engine.prefix, ...words] };
    },
    async release({ sessionId, ref, keepData }) {
      const r = owned(ref);
      await pending.get(sessionId)?.catch(() => void 0);
      await removeCardContainers(r.engine, sessionId);
      if (!keepData && r.worktree) await worktrees.release({ ref: r.worktree, keepData: false });
      return {};
    },
    describe({ ref }) {
      const r = owned(ref);
      return {
        label: `container ${r.image}`.slice(0, 80),
        detail: `${r.engine.kind} ${r.name.slice(0, 18)}\u2026 \xB7 /workspace = ${r.mode === "copy" ? "copy" : "project"} ${r.workspace} \xB7 network ${r.network}`
      };
    },
    owned
  };
}

// src/services/container.mjs
var environment = null;
var host = null;
var dataDir = null;
var ready = () => {
  if (!environment) throw new Error("The container service is starting; try again.");
  return environment;
};
var readSettings = async () => await host.callHost("storage.get", { key: CONTAINER_SETTINGS_KEY }) ?? null;
serve({
  onInitialize: ({ dataDir: folder }, connection) => {
    host = connection;
    dataDir = folder;
    environment = createContainerEnvironment({ dataDir, readSettings });
  },
  methods: {
    "canvastty.environment.prepare": (params) => ready().prepare(params),
    "canvastty.environment.resume": (params) => ready().resume(params),
    "canvastty.environment.wrap": (params) => ready().wrap(params),
    "canvastty.environment.release": (params) => ready().release(params),
    "canvastty.environment.describe": (params) => ready().describe(params),
    // From the settings page: which engine runs here, and is the image there?
    async check() {
      ready();
      const settings = normalizeContainerSettings(await readSettings());
      try {
        const engine = await detectLocalEngine({ preferred: settings.engine, dataDir });
        const where = `${engine.kind === "docker" ? "Docker" : "Podman"}${engine.rootless ? " (rootless)" : ""} runs on this computer`;
        if (!settings.image) return { ok: false, message: `${where}; no image is set yet.` };
        try {
          parseImage(await runEngine(engine, ["image", "inspect", settings.image], { timeoutMs: 6e3 }));
          return { ok: true, message: `${where}; the image ${settings.image} is there.` };
        } catch (error) {
          return { ok: false, message: `${where}, but the image ${settings.image} cannot be used: ${error.message}` };
        }
      } catch (error) {
        return { ok: false, message: error.message };
      }
    }
  }
});
