// Generated by scripts/build.mjs from src/; edit the sources, not this file.

// src/rpc.mjs
var RPC_LIMITS = Object.freeze({
  /** CanvasTTY caps service frames at 1 MiB in both directions. */
  frameBytes: 1048576,
  hostCallMs: 3e4,
  hostCalls: 64,
  activeHandlers: 64,
  /** CanvasTTY waits 2 s after canvastty.shutdown before SIGTERM. */
  drainMs: 1500
});
function serve({ methods, notifications = {}, onInitialize, input = process.stdin, output = process.stdout, exit = (code) => process.exit(code), limits = {} }) {
  const limit = { ...RPC_LIMITS, ...limits };
  const pending = /* @__PURE__ */ new Map();
  let nextId = 1;
  let active = 0;
  let stopping = false;
  let hostGone = false;
  let onIdle = null;
  const send = (message) => output.write(`${JSON.stringify({ jsonrpc: "2.0", ...message })}
`);
  const callHost = (method, params) => new Promise((resolve, reject) => {
    if (hostGone) return reject(new Error("The host connection is closed."));
    if (pending.size >= limit.hostCalls) return reject(new Error("Too many host calls in flight."));
    const id = nextId++;
    const timer = setTimeout(() => {
      pending.delete(id);
      reject(new Error(`The host did not answer ${method} in time.`));
    }, limit.hostCallMs);
    pending.set(id, { resolve, reject, timer });
    send({ id, method, params });
  });
  const log = (level, message) => send({ method: "log", params: { level, message: String(message).slice(0, 500) } });
  const context = { callHost, log };
  const errorText = (error) => String(error?.message ?? error);
  const track = (run) => {
    active++;
    return Promise.resolve().then(run).finally(() => {
      active--;
      if (active === 0) onIdle?.();
    });
  };
  const stop = () => {
    if (stopping) return;
    stopping = true;
    const timer = setTimeout(() => exit(0), limit.drainMs);
    onIdle = () => {
      clearTimeout(timer);
      exit(0);
    };
    if (active === 0) onIdle();
  };
  const handle = (line) => {
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      return;
    }
    if (!message || typeof message !== "object" || Array.isArray(message)) return;
    if (message.method === "canvastty.initialize") {
      Promise.resolve().then(() => onInitialize?.(message.params, context)).catch((error) => log("error", `initialize failed: ${errorText(error)}`));
      return;
    }
    if (message.method === "canvastty.shutdown") return stop();
    if (typeof message.method === "string" && message.id === void 0) {
      if (stopping) return;
      if (active >= limit.activeHandlers) return log("warn", `${message.method}: dropped, the service is busy`);
      const handler = Object.hasOwn(notifications, message.method) ? notifications[message.method] : void 0;
      track(() => handler?.(message.params, context)).catch((error) => log("warn", `${message.method}: ${errorText(error)}`));
      return;
    }
    if (typeof message.method === "string") {
      if (stopping || active >= limit.activeHandlers) {
        send({ id: message.id, error: { code: -32e3, message: stopping ? "The service is stopping." : "The service is busy; try again." } });
        return;
      }
      const method = Object.hasOwn(methods, message.method) ? methods[message.method] : void 0;
      track(() => {
        if (!method) throw Object.assign(new Error(`Unknown method: ${message.method}`), { code: -32601 });
        return method(message.params ?? {}, context);
      }).then(
        (result) => send({ id: message.id, result: result ?? null }),
        (error) => send({ id: message.id, error: { code: error?.code ?? -32e3, message: errorText(error).slice(0, 400) } })
      );
      return;
    }
    const waiter = typeof message.id === "number" ? pending.get(message.id) : void 0;
    if (!waiter) return;
    pending.delete(message.id);
    clearTimeout(waiter.timer);
    if (message.error) waiter.reject(new Error(typeof message.error.message === "string" ? message.error.message : "Host request failed."));
    else waiter.resolve(message.result);
  };
  let chunks = [];
  let size = 0;
  let skipping = false;
  const drop = () => {
    if (!skipping) log("warn", "Dropped a host message larger than the frame limit.");
    chunks = [];
    size = 0;
  };
  input.on("data", (data) => {
    let chunk = typeof data === "string" ? Buffer.from(data) : data;
    for (let newline = chunk.indexOf(10); newline >= 0; newline = chunk.indexOf(10)) {
      const part = chunk.subarray(0, newline);
      chunk = chunk.subarray(newline + 1);
      if (skipping || size + part.length > limit.frameBytes) {
        drop();
        skipping = false;
        continue;
      }
      const line = (chunks.length ? Buffer.concat([...chunks, part]) : part).toString("utf8");
      chunks = [];
      size = 0;
      handle(line);
    }
    if (!chunk.length || skipping) return;
    if (size + chunk.length > limit.frameBytes) {
      drop();
      skipping = true;
      return;
    }
    chunks.push(Buffer.from(chunk));
    size += chunk.length;
  });
  const closed = () => {
    if (hostGone) return;
    hostGone = true;
    for (const waiter of pending.values()) {
      clearTimeout(waiter.timer);
      waiter.reject(new Error("The host connection closed."));
    }
    pending.clear();
    stop();
  };
  input.on("end", closed);
  input.on("error", closed);
}

// src/sshHost.mjs
import { execFile } from "node:child_process";
import { realpathSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { dirname } from "node:path";

// src/hosts.mjs
var MAX_HOSTS = 16;
var MAX_WORKSPACES = 8;
var MAX_PATH = 4096;
var CONTROL = /[\u0000-\u001f\u007f]/u;
function hostInvalidReason(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "a host must be an object";
  const unknown = Object.keys(value).find((key) => !["label", "sshHost", "sshUser", "sshPort", "workspaces"].includes(key));
  if (unknown) return `unknown field ${unknown.slice(0, 40)}`;
  if (typeof value.label !== "string" || !value.label.trim() || value.label.length > 40 || CONTROL.test(value.label)) {
    return "label must be 1 to 40 characters";
  }
  if (typeof value.sshHost !== "string" || !value.sshHost || value.sshHost.length > 253 || /\s/u.test(value.sshHost) || value.sshHost.startsWith("-") || value.sshHost.includes("@") || CONTROL.test(value.sshHost)) {
    return "SSH host must be an ssh config alias or a host name, without spaces, @ or a leading dash";
  }
  if (value.sshUser !== void 0 && (typeof value.sshUser !== "string" || !value.sshUser || value.sshUser.length > 64 || /[\s@]/u.test(value.sshUser) || value.sshUser.startsWith("-") || CONTROL.test(value.sshUser))) {
    return "user must be a name without spaces, @ or a leading dash";
  }
  if (value.sshPort !== void 0 && (!Number.isInteger(value.sshPort) || value.sshPort < 1 || value.sshPort > 65535)) {
    return "port must be a number from 1 to 65535";
  }
  const workspaces = value.workspaces ?? [];
  if (!Array.isArray(workspaces) || workspaces.length > MAX_WORKSPACES) return `at most ${MAX_WORKSPACES} folder mappings`;
  const locals = /* @__PURE__ */ new Set();
  for (const workspace of workspaces) {
    if (!workspace || typeof workspace !== "object" || Object.keys(workspace).sort().join() !== "localPath,remotePath") {
      return "a folder mapping has exactly localPath and remotePath";
    }
    if (!isAbsolutePosix(workspace.localPath)) return "the folder on this computer must be an absolute path";
    if (!isAbsolutePosix(workspace.remotePath)) return "the folder on the server must be an absolute path";
    const key = trimSlashes(workspace.localPath);
    if (locals.has(key)) return "each folder on this computer is mapped once";
    locals.add(key);
  }
  return null;
}
function normalizeHosts(value) {
  if (!Array.isArray(value)) return [];
  const seen = /* @__PURE__ */ new Set();
  const hosts = [];
  for (const host2 of value.slice(0, MAX_HOSTS)) {
    if (hostInvalidReason(host2) !== null || seen.has(host2.label.trim().toLowerCase())) continue;
    seen.add(host2.label.trim().toLowerCase());
    hosts.push(structuredClone({ ...host2, label: host2.label.trim(), workspaces: host2.workspaces ?? [] }));
  }
  return hosts;
}
function chooseHost(hosts, wanted) {
  const name = typeof wanted === "string" ? wanted.trim().toLowerCase() : "";
  if (!name) return hosts[0] ?? null;
  return hosts.find((host2) => host2.label.toLowerCase() === name) ?? hosts.find((host2) => host2.sshHost.toLowerCase() === name) ?? null;
}
function remoteFolderFor(host2, localFolder) {
  if (!isAbsolutePosix(localFolder)) return null;
  const wanted = trimSlashes(localFolder);
  let best = null;
  for (const { localPath, remotePath } of host2.workspaces ?? []) {
    const root = trimSlashes(localPath);
    const inside = wanted === root ? "" : wanted.startsWith(root === "/" ? "/" : `${root}/`) ? wanted.slice(root === "/" ? 1 : root.length + 1) : null;
    if (inside === null || best && best.root.length >= root.length) continue;
    best = { root, folder: inside ? `${trimSlashes(remotePath)}/${inside}`.replace(/^\/\//u, "/") : remotePath };
  }
  return best ? best.folder : null;
}
function destinationArgs(host2) {
  if (hostInvalidReason({ ...host2, label: host2.label || "host" }) !== null) throw new Error("The host settings are invalid.");
  return [...host2.sshPort ? ["-p", String(host2.sshPort)] : [], "--", host2.sshUser ? `${host2.sshUser}@${host2.sshHost}` : host2.sshHost];
}
function shellQuote(word) {
  if (typeof word !== "string" || word.includes("\0")) throw new Error("A value cannot be passed to the remote shell.");
  return `'${word.replaceAll("'", "'\\''")}'`;
}
var SAFE_PROGRAM = /^[A-Za-z0-9_][A-Za-z0-9._-]*$/u;
function remoteCommandLine({ provider, remoteFolder, command, args = [], localRoots = [] }) {
  if (!isAbsolutePosix(remoteFolder)) throw new Error("The folder on the server cannot be used.");
  const cd = `cd ${shellQuote(remoteFolder)}`;
  if (provider === "terminal") return `${cd} && exec "\${SHELL:-/bin/sh}" -l`;
  const program = String(command).split("/").pop();
  if (!SAFE_PROGRAM.test(program)) throw new Error(`The agent program ${JSON.stringify(program)} cannot be started over ssh.`);
  const invocation = ["exec", program, ...remoteArgs(args, localRoots)].map((word, index) => index < 2 ? word : shellQuote(word)).join(" ");
  return `${cd} && exec "\${SHELL:-/bin/sh}" -lc ${shellQuote(invocation)}`;
}
var LOCAL_VALUE_FLAGS = /* @__PURE__ */ new Set([
  "--settings",
  "--mcp-config",
  "--mcp-config-file",
  "-c",
  "--config",
  "--append-system-prompt-file",
  "--system-prompt-file",
  "--add-dir",
  "--plugin-dir"
]);
function remoteArgs(args, localRoots) {
  const roots = localRoots.filter((root) => typeof root === "string" && root.length > 1).map(trimSlashes);
  const local = (word) => /^\s*[{[]/u.test(word) || roots.some((root) => word.includes(root));
  const kept = [];
  for (const word of args) {
    if (typeof word !== "string" || word.includes("\0")) throw new Error("Invalid agent argument.");
    if (!local(word)) {
      kept.push(word);
      continue;
    }
    const previous = kept.at(-1);
    if (!word.startsWith("-") && previous !== void 0 && LOCAL_VALUE_FLAGS.has(previous)) kept.pop();
  }
  return kept;
}
function sshLaunchArgs(host2, remoteLine) {
  return ["-tt", "-o", "ForwardAgent=no", "-o", "ClearAllForwardings=yes", "-o", "ServerAliveInterval=30", ...destinationArgs(host2), remoteLine];
}
function sshBatchArgs(host2, remoteLine, connectTimeoutSeconds = 8) {
  return [
    "-T",
    "-o",
    "BatchMode=yes",
    "-o",
    `ConnectTimeout=${connectTimeoutSeconds}`,
    "-o",
    "ForwardAgent=no",
    "-o",
    "ClearAllForwardings=yes",
    ...destinationArgs(host2),
    remoteLine
  ];
}
function hostSnapshot(host2) {
  return { label: host2.label, sshHost: host2.sshHost, ...host2.sshUser ? { sshUser: host2.sshUser } : {}, ...host2.sshPort ? { sshPort: host2.sshPort } : {} };
}
function isAbsolutePosix(value) {
  return typeof value === "string" && value.startsWith("/") && value.length <= MAX_PATH && !CONTROL.test(value) && !value.split("/").includes("..");
}
function trimSlashes(path) {
  return path === "/" ? path : path.replace(/\/+$/u, "");
}

// src/sshHost.mjs
var HOSTS_KEY = "hosts";
function runSsh(args, timeoutMs, { ssh = "ssh" } = {}) {
  return new Promise((resolve) => {
    const child = execFile(ssh, args, { timeout: timeoutMs, killSignal: "SIGKILL", maxBuffer: 64 * 1024 }, (error, _stdout, stderr) => {
      if (!error) return resolve({ code: 0, stderr: "" });
      const timedOut = error.killed === true || error.signal === "SIGKILL";
      resolve({ code: typeof error.code === "number" ? error.code : null, stderr: String(stderr || error.message), timedOut });
    });
    child.stdin?.end();
  });
}
async function checkRemoteFolder(host2, remoteFolder, { timeoutMs, ssh } = {}) {
  const result = await runSsh(
    sshBatchArgs(host2, `test -d ${shellQuote(remoteFolder)}`, Math.max(1, Math.floor((timeoutMs - 1e3) / 1e3))),
    timeoutMs,
    { ssh }
  );
  if (result.code === 0) return null;
  if (result.timedOut) return `${host2.label} (${host2.sshHost}) did not answer within ${Math.round(timeoutMs / 1e3)} s.`;
  if (result.code === 1) return `The folder ${remoteFolder} does not exist on ${host2.label}.`;
  const detail = result.stderr.replace(/\s+/gu, " ").trim().slice(0, 160);
  return `${host2.label} (${host2.sshHost}) cannot be reached over ssh${detail ? `: ${detail}` : ""}.`;
}
function createSshHostEnvironment({ dataDir, readHosts: readHosts2, ssh = "ssh", checkTimeoutMs = 8e3 }) {
  const localRoots = localRootsFor(dataDir);
  const refOf = (ref) => {
    if (!ref || typeof ref !== "object" || typeof ref.remoteFolder !== "string" || !ref.host) throw new Error("This card's server ref is unreadable.");
    return ref;
  };
  return {
    async prepare({ cwd, options = {} }) {
      const hosts = normalizeHosts(await readHosts2());
      if (hosts.length === 0) return { refuse: { reason: "No server is configured yet: add one in the plugin's settings (Extensions \u2192 CanvasTTY Environments \u2192 Settings)." } };
      const host2 = chooseHost(hosts, options.host);
      if (!host2) return { refuse: { reason: `No configured server is called ${String(options.host).slice(0, 40)}.` } };
      const remoteFolder = remoteFolderFor(host2, cwd);
      if (!remoteFolder) return { refuse: { reason: `${cwd} is not mapped to a folder on ${host2.label}; add a folder mapping in the plugin's settings.` } };
      const problem = await checkRemoteFolder(host2, remoteFolder, { timeoutMs: checkTimeoutMs, ssh });
      if (problem) return { refuse: { reason: problem } };
      return { ref: { host: hostSnapshot(host2), remoteFolder, localFolder: cwd }, label: `ssh ${host2.label}` };
    },
    async resume({ ref }) {
      const { host: host2, remoteFolder } = refOf(ref);
      const problem = await checkRemoteFolder(host2, remoteFolder, { timeoutMs: checkTimeoutMs, ssh });
      return problem ? { stopped: { reason: problem } } : { ok: true };
    },
    wrap({ ref, provider, command, args }) {
      const { host: host2, remoteFolder } = refOf(ref);
      return { command: "ssh", args: sshLaunchArgs(host2, remoteCommandLine({ provider, remoteFolder, command, args, localRoots })) };
    },
    // The server's folder is the person's: nothing is removed there, with or without "keep data".
    release() {
      return {};
    },
    describe({ ref }) {
      const { host: host2, remoteFolder } = refOf(ref);
      const destination = `${host2.sshUser ? `${host2.sshUser}@` : ""}${host2.sshHost}${host2.sshPort ? `:${host2.sshPort}` : ""}`;
      return { label: `ssh ${host2.label}`, detail: `${destination} ${remoteFolder}` };
    }
  };
}
function localRootsFor(dataDir) {
  return [...new Set([
    homedir(),
    tmpdir(),
    safeRealpath(tmpdir()),
    "/private/var/folders",
    "/var/folders",
    dirname(dirname(dataDir)),
    appRoot(process.execPath)
  ].filter(Boolean))];
}
function safeRealpath(path) {
  try {
    return realpathSync(path);
  } catch {
    return null;
  }
}
function appRoot(execPath) {
  const bundle = execPath.indexOf(".app/");
  return bundle > 0 ? execPath.slice(0, bundle + 4) : dirname(execPath);
}

// src/services/ssh-host.mjs
var environment = null;
var host = null;
var ready = () => {
  if (!environment) throw new Error("The ssh-host service is starting; try again.");
  return environment;
};
var readHosts = async () => await host.callHost("storage.get", { key: HOSTS_KEY }) ?? [];
serve({
  onInitialize: ({ dataDir }, connection) => {
    host = connection;
    environment = createSshHostEnvironment({ dataDir, readHosts });
  },
  methods: {
    "canvastty.environment.prepare": (params) => ready().prepare(params),
    "canvastty.environment.resume": (params) => ready().resume(params),
    "canvastty.environment.wrap": (params) => ready().wrap(params),
    "canvastty.environment.release": (params) => ready().release(params),
    "canvastty.environment.describe": (params) => ready().describe(params),
    // From the settings page: is this server reachable, and (optionally) is a folder mapped and present there?
    async check({ label, folder }) {
      const hosts = normalizeHosts(await readHosts());
      const chosen = chooseHost(hosts, label);
      if (!chosen) return { ok: false, message: "No such server in the saved settings." };
      const remote = folder ? remoteFolderFor(chosen, folder) : chosen.workspaces[0]?.remotePath ?? "/";
      if (!remote) return { ok: false, message: `${folder} is not mapped on ${chosen.label}.` };
      const problem = await checkRemoteFolder(chosen, remote, { timeoutMs: 8e3 });
      return problem ? { ok: false, message: problem } : { ok: true, message: `${chosen.label} answers; ${remote} exists.` };
    }
  }
});
