// Generated by scripts/build.mjs from src/; edit the sources, not this file.

// src/rpc.mjs
import { createInterface } from "node:readline";
function serve({ methods, notifications = {}, onInitialize }) {
  const pending = /* @__PURE__ */ new Map();
  let nextId = 1;
  const send = (message) => process.stdout.write(`${JSON.stringify({ jsonrpc: "2.0", ...message })}
`);
  const callHost = (method, params) => new Promise((resolve2, reject) => {
    const id = nextId++;
    pending.set(id, { resolve: resolve2, reject });
    send({ id, method, params });
  });
  const log = (level, message) => send({ method: "log", params: { level, message: String(message).slice(0, 500) } });
  createInterface({ input: process.stdin }).on("line", (line) => {
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      return;
    }
    if (message.method === "canvastty.initialize") {
      Promise.resolve().then(() => onInitialize?.(message.params, { callHost, log })).catch((error) => log("error", `initialize failed: ${error.message}`));
      return;
    }
    if (message.method === "canvastty.shutdown") process.exit(0);
    if (typeof message.method === "string" && message.id === void 0) {
      Promise.resolve().then(() => notifications[message.method]?.(message.params, { callHost, log })).catch((error) => log("warn", `${message.method}: ${error.message}`));
      return;
    }
    if (typeof message.method === "string") {
      const method = methods[message.method];
      Promise.resolve().then(() => {
        if (!method) throw Object.assign(new Error(`Unknown method: ${message.method}`), { code: -32601 });
        return method(message.params ?? {}, { callHost, log });
      }).then(
        (result) => send({ id: message.id, result: result ?? null }),
        (error) => send({ id: message.id, error: { code: error.code ?? -32e3, message: String(error.message).slice(0, 400) } })
      );
      return;
    }
    const waiter = pending.get(message.id);
    if (!waiter) return;
    pending.delete(message.id);
    if (message.error) waiter.reject(new Error(message.error.message));
    else waiter.resolve(message.result);
  }).on("close", () => process.exit(0));
}

// src/worktree.mjs
import { execFile } from "node:child_process";
import { existsSync, realpathSync } from "node:fs";
import { basename, join, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";
var run = promisify(execFile);
var git = async (cwd, ...args) => (await run("git", ["-C", cwd, ...args], { timeout: 1e4 })).stdout.trim();
function createWorktreeEnvironment({ dataDir }) {
  const root = resolve(dataDir, "worktrees");
  function owned(ref) {
    const dir = typeof ref?.dir === "string" ? resolve(ref.dir) : "";
    if (!dir.startsWith(root + sep)) throw new Error("This worktree does not belong to the plugin.");
    return { ...ref, dir };
  }
  return {
    async prepare({ sessionId, cwd, options = {} }) {
      const repo = await git(cwd, "rev-parse", "--show-toplevel").catch(() => null);
      if (!repo) return { refuse: { reason: `${cwd} is not inside a git repository.` } };
      const base = await git(repo, "rev-parse", "--verify", "-q", "HEAD^{commit}").catch(() => null);
      if (!base) return { refuse: { reason: `${repo} has no commit yet; commit once before starting a worktree.` } };
      const branch = String(options.branch ?? "").trim() || `canvastty/${String(sessionId).slice(0, 8)}`;
      if (!await git(repo, "check-ref-format", "--branch", branch).catch(() => null)) {
        return { refuse: { reason: `${branch} is not a valid branch name.` } };
      }
      const dir = join(root, `${basename(repo)}-${String(sessionId).slice(0, 8)}`);
      const exists = await git(repo, "rev-parse", "--verify", "--quiet", `refs/heads/${branch}`).then(() => true, () => false);
      try {
        await git(repo, "worktree", "add", "--quiet", ...exists ? [dir, branch] : ["-b", branch, dir]);
      } catch (error) {
        return { refuse: { reason: `git worktree add failed: ${String(error.stderr || error.message).trim().slice(0, 200)}` } };
      }
      const started = await git(dir, "rev-parse", "HEAD");
      const inside = relative(repo, realpathSync(cwd));
      const sub = inside.startsWith("..") ? "" : inside;
      return { ref: { repo, dir, branch, createdBranch: !exists, sub, base: started }, label: `worktree ${branch}`, cwd: join(dir, sub) };
    },
    async resume({ ref }) {
      const { dir } = owned(ref);
      if (!existsSync(dir)) return { stopped: { reason: `The worktree folder ${dir} no longer exists.` } };
      const inside = await git(dir, "rev-parse", "--is-inside-work-tree").catch(() => "");
      return inside === "true" ? { ok: true } : { stopped: { reason: `${dir} is no longer a git worktree.` } };
    },
    wrap({ ref, command, args }) {
      const { dir, sub } = owned(ref);
      return { command, args, cwd: join(dir, sub ?? "") };
    },
    async release({ ref, keepData }) {
      if (keepData) return {};
      const { repo, dir, branch, createdBranch } = owned(ref);
      await git(repo, "worktree", "remove", "--force", dir);
      if (createdBranch) await git(repo, "branch", "-D", branch).catch(() => void 0);
      return {};
    },
    async describe({ ref }) {
      const { dir } = owned(ref);
      const branch = await git(dir, "rev-parse", "--abbrev-ref", "HEAD").catch(() => ref.branch);
      return { label: `worktree ${branch}`, detail: dir };
    },
    /** For "Collect changes": the worktree folder and the commit it started from, after the ownership check. */
    owned
  };
}

// src/services/worktree.mjs
var environment = null;
var ready = () => {
  if (!environment) throw new Error("The worktree service is starting; try again.");
  return environment;
};
serve({
  onInitialize: ({ dataDir }) => {
    environment = createWorktreeEnvironment({ dataDir });
  },
  methods: {
    "canvastty.environment.prepare": (params) => ready().prepare(params),
    "canvastty.environment.resume": (params) => ready().resume(params),
    "canvastty.environment.wrap": (params) => ready().wrap(params),
    "canvastty.environment.release": (params) => ready().release(params),
    "canvastty.environment.describe": (params) => ready().describe(params)
  }
});
