// Generated by scripts/build.mjs from src/; edit the sources, not this file.

// src/rpc.mjs
var RPC_LIMITS = Object.freeze({
  /** CanvasTTY caps service frames at 1 MiB in both directions. */
  frameBytes: 1048576,
  hostCallMs: 3e4,
  hostCalls: 64,
  activeHandlers: 64,
  /** CanvasTTY waits 2 s after canvastty.shutdown before SIGTERM. */
  drainMs: 1500
});
function serve({ methods, notifications = {}, onInitialize, input = process.stdin, output = process.stdout, exit = (code) => process.exit(code), limits = {} }) {
  const limit = { ...RPC_LIMITS, ...limits };
  const pending = /* @__PURE__ */ new Map();
  let nextId = 1;
  let active = 0;
  let stopping = false;
  let hostGone = false;
  let onIdle = null;
  const send = (message) => output.write(`${JSON.stringify({ jsonrpc: "2.0", ...message })}
`);
  const callHost = (method, params) => new Promise((resolve2, reject) => {
    if (hostGone) return reject(new Error("The host connection is closed."));
    if (pending.size >= limit.hostCalls) return reject(new Error("Too many host calls in flight."));
    const id = nextId++;
    const timer = setTimeout(() => {
      pending.delete(id);
      reject(new Error(`The host did not answer ${method} in time.`));
    }, limit.hostCallMs);
    pending.set(id, { resolve: resolve2, reject, timer });
    send({ id, method, params });
  });
  const log = (level, message) => send({ method: "log", params: { level, message: String(message).slice(0, 500) } });
  const context = { callHost, log };
  const errorText = (error) => String(error?.message ?? error);
  const track = (run2) => {
    active++;
    return Promise.resolve().then(run2).finally(() => {
      active--;
      if (active === 0) onIdle?.();
    });
  };
  const stop = () => {
    if (stopping) return;
    stopping = true;
    const timer = setTimeout(() => exit(0), limit.drainMs);
    onIdle = () => {
      clearTimeout(timer);
      exit(0);
    };
    if (active === 0) onIdle();
  };
  const handle = (line) => {
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      return;
    }
    if (!message || typeof message !== "object" || Array.isArray(message)) return;
    if (message.method === "canvastty.initialize") {
      Promise.resolve().then(() => onInitialize?.(message.params, context)).catch((error) => log("error", `initialize failed: ${errorText(error)}`));
      return;
    }
    if (message.method === "canvastty.shutdown") return stop();
    if (typeof message.method === "string" && message.id === void 0) {
      if (stopping) return;
      if (active >= limit.activeHandlers) return log("warn", `${message.method}: dropped, the service is busy`);
      const handler = Object.hasOwn(notifications, message.method) ? notifications[message.method] : void 0;
      track(() => handler?.(message.params, context)).catch((error) => log("warn", `${message.method}: ${errorText(error)}`));
      return;
    }
    if (typeof message.method === "string") {
      if (stopping || active >= limit.activeHandlers) {
        send({ id: message.id, error: { code: -32e3, message: stopping ? "The service is stopping." : "The service is busy; try again." } });
        return;
      }
      const method = Object.hasOwn(methods, message.method) ? methods[message.method] : void 0;
      track(() => {
        if (!method) throw Object.assign(new Error(`Unknown method: ${message.method}`), { code: -32601 });
        return method(message.params ?? {}, context);
      }).then(
        (result) => send({ id: message.id, result: result ?? null }),
        (error) => send({ id: message.id, error: { code: error?.code ?? -32e3, message: errorText(error).slice(0, 400) } })
      );
      return;
    }
    const waiter = typeof message.id === "number" ? pending.get(message.id) : void 0;
    if (!waiter) return;
    pending.delete(message.id);
    clearTimeout(waiter.timer);
    if (message.error) waiter.reject(new Error(typeof message.error.message === "string" ? message.error.message : "Host request failed."));
    else waiter.resolve(message.result);
  };
  let chunks = [];
  let size = 0;
  let skipping = false;
  const drop = () => {
    if (!skipping) log("warn", "Dropped a host message larger than the frame limit.");
    chunks = [];
    size = 0;
  };
  input.on("data", (data) => {
    let chunk = typeof data === "string" ? Buffer.from(data) : data;
    for (let newline = chunk.indexOf(10); newline >= 0; newline = chunk.indexOf(10)) {
      const part = chunk.subarray(0, newline);
      chunk = chunk.subarray(newline + 1);
      if (skipping || size + part.length > limit.frameBytes) {
        drop();
        skipping = false;
        continue;
      }
      const line = (chunks.length ? Buffer.concat([...chunks, part]) : part).toString("utf8");
      chunks = [];
      size = 0;
      handle(line);
    }
    if (!chunk.length || skipping) return;
    if (size + chunk.length > limit.frameBytes) {
      drop();
      skipping = true;
      return;
    }
    chunks.push(Buffer.from(chunk));
    size += chunk.length;
  });
  const closed = () => {
    if (hostGone) return;
    hostGone = true;
    for (const waiter of pending.values()) {
      clearTimeout(waiter.timer);
      waiter.reject(new Error("The host connection closed."));
    }
    pending.clear();
    stop();
  };
  input.on("end", closed);
  input.on("error", closed);
}

// src/worktree.mjs
import { execFile } from "node:child_process";
import { existsSync, lstatSync, realpathSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { promisify } from "node:util";
var run = promisify(execFile);
var git = async (cwd, ...args) => (await run("git", ["-C", cwd, ...args], { timeout: 1e4 })).stdout.trim();
function ownedWorktreeFolder(root, value) {
  const dir = typeof value === "string" ? resolve(value) : "";
  const refuse = () => {
    throw new Error("This worktree does not belong to the plugin.");
  };
  if (!dir || dirname(dir) !== root) refuse();
  let info;
  try {
    info = lstatSync(dir);
  } catch (error) {
    if (error.code === "ENOENT") return dir;
    throw error;
  }
  if (!info.isDirectory() || info.isSymbolicLink() || realpathSync(dir) !== join(realpathSync(root), basename(dir))) refuse();
  return dir;
}
async function registeredWorktree(repo, dir) {
  const listing = await git(repo, "worktree", "list", "--porcelain", "-z").catch(() => "");
  const real = (path) => {
    try {
      return realpathSync(path);
    } catch {
      return resolve(path);
    }
  };
  const wanted = real(dir);
  const listed = listing.split("\0").filter((line) => line.startsWith("worktree ")).map((line) => real(line.slice("worktree ".length)));
  if (!listed.includes(wanted)) throw new Error("This worktree is not one of its repository's worktrees.");
}
function createWorktreeEnvironment({ dataDir }) {
  const root = resolve(dataDir, "worktrees");
  function owned(ref) {
    return { ...ref, dir: ownedWorktreeFolder(root, ref?.dir) };
  }
  return {
    async prepare({ sessionId, cwd, options = {} }) {
      const repo = await git(cwd, "rev-parse", "--show-toplevel").catch(() => null);
      if (!repo) return { refuse: { reason: `${cwd} is not inside a git repository.` } };
      const base = await git(repo, "rev-parse", "--verify", "-q", "HEAD^{commit}").catch(() => null);
      if (!base) return { refuse: { reason: `${repo} has no commit yet; commit once before starting a worktree.` } };
      const branch = String(options.branch ?? "").trim() || `canvastty/${String(sessionId).slice(0, 8)}`;
      if (!await git(repo, "check-ref-format", "--branch", branch).catch(() => null)) {
        return { refuse: { reason: `${branch} is not a valid branch name.` } };
      }
      const dir = join(root, `${basename(repo)}-${String(sessionId).slice(0, 8)}`);
      const exists = await git(repo, "rev-parse", "--verify", "--quiet", `refs/heads/${branch}`).then(() => true, () => false);
      try {
        await git(repo, "worktree", "add", "--quiet", ...exists ? [dir, branch] : ["-b", branch, dir]);
      } catch (error) {
        return { refuse: { reason: `git worktree add failed: ${String(error.stderr || error.message).trim().slice(0, 200)}` } };
      }
      const started = await git(dir, "rev-parse", "HEAD");
      const inside = relative(repo, realpathSync(cwd));
      const sub = inside.startsWith("..") ? "" : inside;
      return { ref: { repo, dir, branch, createdBranch: !exists, sub, base: started }, label: `worktree ${branch}`, cwd: join(dir, sub) };
    },
    async resume({ ref }) {
      const { dir } = owned(ref);
      if (!existsSync(dir)) return { stopped: { reason: `The worktree folder ${dir} no longer exists.` } };
      const inside = await git(dir, "rev-parse", "--is-inside-work-tree").catch(() => "");
      return inside === "true" ? { ok: true } : { stopped: { reason: `${dir} is no longer a git worktree.` } };
    },
    wrap({ ref, command, args }) {
      const { dir, sub } = owned(ref);
      return { command, args, cwd: join(dir, sub ?? "") };
    },
    async release({ ref, keepData }) {
      if (keepData) return {};
      const { repo, dir, branch, createdBranch } = owned(ref);
      if (typeof repo !== "string") throw new Error("This worktree does not belong to the plugin.");
      await registeredWorktree(repo, dir);
      await git(repo, "worktree", "remove", "--force", dir);
      if (createdBranch) await git(repo, "branch", "-D", branch).catch(() => void 0);
      return {};
    },
    async describe({ ref }) {
      const { dir } = owned(ref);
      const branch = await git(dir, "rev-parse", "--abbrev-ref", "HEAD").catch(() => ref.branch);
      return { label: `worktree ${branch}`, detail: dir };
    },
    /** For "Collect changes": the worktree folder and the commit it started from, after the ownership check. */
    owned
  };
}

// src/services/worktree.mjs
var environment = null;
var ready = () => {
  if (!environment) throw new Error("The worktree service is starting; try again.");
  return environment;
};
serve({
  onInitialize: ({ dataDir }) => {
    environment = createWorktreeEnvironment({ dataDir });
  },
  methods: {
    "canvastty.environment.prepare": (params) => ready().prepare(params),
    "canvastty.environment.resume": (params) => ready().resume(params),
    "canvastty.environment.wrap": (params) => ready().wrap(params),
    "canvastty.environment.release": (params) => ready().release(params),
    "canvastty.environment.describe": (params) => ready().describe(params)
  }
});
