// Builds the installable package in place: CanvasTTY's installer runs no build and no npm install, so the service
// entries are bundled single files (services/*.mjs), the settings page script is one file (settings/hosts.js), and
// the manifest's coreFiles/modules carry the exact bytes and SHA-256 of every file it installs.
//   ESBUILD=/path/to/esbuild node scripts/build.mjs   (default: node_modules/.bin/esbuild)
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const esbuild = process.env.ESBUILD || join(root, "node_modules/.bin/esbuild");
if (!existsSync(esbuild)) throw new Error(`esbuild not found at ${esbuild}; run npm install or set ESBUILD.`);

const banner = "// Generated by scripts/build.mjs from src/; edit the sources, not this file.";
for (const name of ["worktree", "ssh-host", "results"]) {
  execFileSync(esbuild, [`src/services/${name}.mjs`, "--bundle", "--platform=node", "--format=esm", "--target=node20",
    `--outfile=services/${name}.mjs`, `--banner:js=${banner}`, "--log-level=warning"], { cwd: root, stdio: "inherit" });
}
execFileSync(esbuild, ["src/ui/hosts-page.mjs", "--bundle", "--platform=browser", "--format=iife", "--target=es2022",
  "--outfile=settings/hosts.js", `--banner:js=${banner}`, "--log-level=warning"], { cwd: root, stdio: "inherit" });

const manifestPath = join(root, "canvastty.plugin.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const stamp = (file) => {
  const bytes = readFileSync(join(root, file.path));
  return { path: file.path, bytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") };
};
manifest.coreFiles = manifest.coreFiles.map(stamp);
manifest.modules = manifest.modules.map((module) => ({ ...module, files: module.files.map(stamp) }));
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
console.log("built services/, settings/hosts.js and stamped canvastty.plugin.json");
